'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ENDPOINT='https://script.google.com/macros/s/AKfycbylqNpBbGv4TD48T5uuRr_D58r0LkYm6CTAY_V7hKpUD2fTgnlpZRkRV636t1R3_UGhlQ/exec';
const cfg={url:localStorage.getItem('rce_url')||ENDPOINT,pin:localStorage.getItem('rce_pin')||''};
let lang=localStorage.getItem('rce_lang')||'en',page='choose',filter='all',busy=false,reading=false,writeCount=0,lastSync=0,queue=Promise.resolve(),lastError='';
let state={catalog:window.RCE_CATALOG||[],draft:[],favorites:[],orders:[]};
try{const cache=JSON.parse(localStorage.getItem('rce_cached')||'null');if(cache&&Array.isArray(cache.draft))state={...state,...cache}}catch{}
const I={
 subtitle:['Our family grocery list','Danh sách đi chợ gia đình'],navChoose:['🥬 Choose','🥬 Chọn rau'],navReview:['📝 Review','📝 Xem lại'],navShop:['🛒 Shop','🛒 Đi chợ'],chooseTitle:['Choose groceries','Chọn rau củ'],chooseHint:['Tap Add, then adjust the quantity.','Nhấn Thêm rồi chỉnh số lượng.'],filterAll:['All','Tất cả'],filterFav:['⭐ Favourites','⭐ Mua thường'],filterChosen:['✓ Selected','✓ Đã chọn'],customTitle:['＋ Add something else','＋ Thêm món khác'],customSubmit:['Add item','Thêm món'],reviewTitle:['Review your list','Xem lại danh sách'],reviewHint:['You can change anything before submitting.','Bạn có thể sửa trước khi gửi.'],draftNoteLabel:['Note for the shopper','Ghi chú cho người đi chợ'],submitOrder:['📨 Submit shopping list','📨 Gửi danh sách'],submitHint:['You can still edit the submitted order afterwards.','Bạn vẫn có thể sửa đơn sau khi gửi.'],shopTitle:['Shopping mode','Đi chợ'],shopHint:['Tick off your latest active order.','Đánh dấu món đã mua trong đơn mới nhất.'],historyTitle:['Previous orders','Đơn trước'],modalTitle:['Connect Google Sheets','Kết nối Google Sheets'],modalHint:['Enter your household passphrase once on this phone.','Nhập mật khẩu gia đình một lần trên điện thoại này.'],pinLabel:['Household passphrase','Mật khẩu gia đình'],saveConnection:['Connect','Kết nối'],closeModal:['Close','Đóng'],privacyNote:['The passphrase is saved on this device. Do not use this app for sensitive data.','Mật khẩu lưu trên điện thoại này. Không lưu thông tin nhạy cảm.']};
const t=(en,vi)=>lang==='vi'?vi:en;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const product=id=>state.catalog.find(x=>String(x.id)===String(id))||window.RCE_CATALOG.find(x=>x.id===id);
const name=x=>lang==='vi'?(x.vi||x.name||x.en):(x.en||x.name||x.vi);
const other=x=>lang==='vi'?(x.en||''):(x.vi||x.name||'');
const quantity=id=>Number(state.draft.find(x=>String(x.id)===String(id))?.qty||0);
const active=()=>state.orders.find(o=>o.status!=='Completed');
function persist(){try{localStorage.setItem('rce_cached',JSON.stringify(state))}catch{}}
let toastTimer;function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function connection(text,kind=''){const el=$('#connection');el.className='connection '+kind;$('#connectionText').textContent=text}
function api(action,args={}){return new Promise((resolve,reject)=>{
 if(!cfg.url||!cfg.pin)return reject(Error(t('Connect first','Hãy kết nối trước')));
 if(!/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec$/.test(cfg.url))return reject(Error('Invalid Apps Script URL'));
 const cb='rcb_'+Date.now()+'_'+Math.floor(Math.random()*1e9),s=document.createElement('script');let done=false;
 const finish=(err,result)=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];s.remove();err?reject(err):resolve(result)};
 const timer=setTimeout(()=>finish(Error(t('Google Sheets timed out. Try refresh.','Google Sheets quá thời gian. Thử tải lại.'))),35000);
 window[cb]=r=>r&&r.ok?finish(null,r.data):finish(Error(r?.error||'Server error'));
 s.onerror=()=>finish(Error(t('Could not reach Apps Script','Không kết nối được Apps Script')));
 s.src=cfg.url+'?'+new URLSearchParams({callback:cb,pin:cfg.pin,action,...args,_:String(Date.now())});document.head.appendChild(s);
})}
async function sync(show=false){if(!cfg.pin||reading||busy||writeCount)return;reading=true;if(show||!lastSync)connection(t('Connecting…','Đang kết nối…'));
 try{const result=await api('read');if(!busy&&!writeCount){state={...result,catalog:result.catalog?.length?result.catalog:window.RCE_CATALOG};persist();lastSync=Date.now();lastError='';connection(t('Synced','Đã đồng bộ'),'ok');render()}}
 catch(e){lastError=e.message;connection(t('Offline · Retry','Mất kết nối · Thử lại'),'bad');if(show)toast(e.message)}finally{reading=false}}
function write(action,args={},optimistic){if(optimistic){optimistic();persist();render()}writeCount++;connection(t('Saving…','Đang lưu…'));
 const job=queue.then(async()=>{while(reading)await new Promise(r=>setTimeout(r,70));busy=true;let ok=false;
 try{const result=await api(action,args);ok=true;lastSync=Date.now();lastError='';if(writeCount===1){state={...result,catalog:result.catalog?.length?result.catalog:window.RCE_CATALOG};persist();render()}connection(t('Saved','Đã lưu'),'ok')}
 catch(e){lastError=e.message;connection(t('Save failed · Retry','Lỗi lưu · Thử lại'),'bad');toast(t('Not saved: ','Chưa lưu: ')+e.message)}
 finally{busy=false;writeCount--;if(!writeCount)setTimeout(()=>sync(false),250)}return ok});queue=job.then(()=>{},()=>{});return job}
function setPage(next){page=next;$$('.page').forEach(el=>el.classList.toggle('hidden',el.id!==next));$$('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===next));$('#bottomCTA').classList.toggle('hidden',next==='shop');render();window.scrollTo({top:0,behavior:'smooth'})}
function applyLang(){document.documentElement.lang=lang;for(const [id,pair] of Object.entries(I)){const el=document.getElementById(id);if(el)el.textContent=pair[lang==='vi'?1:0]}$('#search').placeholder=t('Search in English or Vietnamese','Tìm bằng tiếng Việt hoặc tiếng Anh');$('#customName').placeholder=t('e.g. Pork, ginger, milk','Ví dụ: Thịt heo, gừng, sữa');$('#draftNote').placeholder=t('Anything to remember?','Có cần dặn gì không?');$$('[data-lang]').forEach(el=>el.classList.toggle('selected',el.dataset.lang===lang))}
function render(){applyLang();const n=state.draft.length;$('#badgeCount').textContent=n?'('+n+')':'';$('#bottomSummary').textContent=t(`${n} item${n===1?'':'s'} selected`,`${n} món đã chọn`);$('#bottomAction').textContent=page==='review'?t('Choose more +','Chọn thêm +'):t('Review list →','Xem danh sách →');renderProducts();renderDraft();renderOrders()}
function renderProducts(){const q=$('#search').value.toLocaleLowerCase().trim(),fav=state.favorites||[];const products=(state.catalog?.length?state.catalog:window.RCE_CATALOG).filter(p=>(p.vi+' '+p.en).toLocaleLowerCase().includes(q)&&(filter==='all'||(filter==='fav'&&fav.includes(p.id))||(filter==='chosen'&&quantity(p.id)>0)));
 $('#products').innerHTML=products.map(p=>{const n=quantity(p.id),star=fav.includes(p.id);return `<article class="product"><button class="fav ${star?'on':''}" data-fav="${esc(p.id)}" aria-label="${star?t('Remove favourite','Bỏ yêu thích'):t('Add favourite','Yêu thích')}" aria-pressed="${star}">${star?'★':'☆'}</button><img src="${esc(p.image)}" alt="${esc(name(p))}" loading="lazy"><div class="productbody"><strong>${esc(name(p))}</strong><div class="secondaryname">${esc(other(p))}</div>${n?stepper(p.id,n,'draft'):`<button class="add" data-adjust="${esc(p.id)}" data-delta="1">＋ ${t('Add','Thêm')}</button>`}</div></article>`}).join('')||`<div class="empty">${t('No matching vegetables.','Không tìm thấy rau củ.')}</div>`}
function stepper(id,n,scope,oid=''){const attr=scope==='order'?`data-order-id="${esc(oid)}"`:'';return `<div class="stepper"><button aria-label="Decrease" data-${scope}-id="${esc(id)}" ${attr} data-delta="-1">−</button><span class="number">${n}</span><button aria-label="Increase" data-${scope}-id="${esc(id)}" ${attr} data-delta="1">+</button></div>`}
function renderDraft(){const d=state.draft||[];$('#draftItems').innerHTML=d.length?d.map(x=>`<div class="lineitem"><img src="${esc(x.image||'')}" alt="" onerror="this.style.opacity='.15'"><div><b>${esc(name(x))}</b><div class="small">${esc(other(x))} · ${esc(x.unit||'')}</div></div>${stepper(x.id,Number(x.qty),'draft')}</div>`).join(''):`<div class="empty">${t('Your list is empty. Add some groceries first.','Danh sách trống. Hãy chọn món trước.')}</div>`;$('#submitOrder').disabled=!d.length||writeCount>0}
function orderHtml(o,editable){const bought=o.items.filter(i=>i.bought).length,total=o.items.length;return `<div class="order"><div class="orderhead"><div><h3>${editable?t('Current shopping list','Danh sách đang mua'):t('Completed order','Đơn đã xong')}</h3><div class="hint">${esc(new Date(o.submittedAt).toLocaleString(lang==='vi'?'vi-VN':'en-AU'))}</div></div><span>${editable?'🛒':'✅'}</span></div><div class="progress"><div style="width:${total?bought/total*100:0}%"></div></div><p class="hint">${t(`${bought} of ${total} purchased`, `Đã mua ${bought}/${total} món`)}</p>${o.note?`<p>📝 ${esc(o.note)}</p>`:''}${[...o.items].sort((a,b)=>Number(a.bought)-Number(b.bought)).map(i=>`<div class="lineitem ${i.bought?'bought':''}"><img src="${esc(i.image||'')}" alt=""><div><div class="itemname"><b>${esc(name(i))}</b></div><div class="small">${esc(other(i))} · ${esc(i.unit||'')}</div>${editable?stepper(i.itemId,Number(i.qty),'order',o.orderId):`<b>${Number(i.qty)}</b>`}</div><input type="checkbox" data-bought="${esc(i.itemId)}" data-oid="${esc(o.orderId)}" ${i.bought?'checked':''} ${editable?'':'disabled'} aria-label="${t('Purchased','Đã mua')} ${esc(name(i))}"></div>`).join('')}${editable?`<div class="addrow"><select id="orderAddSelect">${(state.catalog?.length?state.catalog:window.RCE_CATALOG).map(p=>`<option value="${esc(p.id)}">${esc(name(p))}</option>`).join('')}</select><button class="secondary" data-add-order="${esc(o.orderId)}">＋ ${t('Add','Thêm')}</button></div>`:''}<div class="ordercontrols"><button class="secondary" data-note="${esc(o.orderId)}">✏️ ${t('Edit note','Sửa ghi chú')}</button>${editable?`<button class="primary" data-finish="${esc(o.orderId)}">✓ ${t('Finish trip','Xong đi chợ')}</button>`:`<button class="secondary" data-repeat="${esc(o.orderId)}">↻ ${t('Repeat','Mua lại')}</button>`}</div></div>`}
function renderOrders(){const o=active();$('#activeOrder').innerHTML=o?orderHtml(o,true):`<div class="panel empty">${t('No active order yet. Submit a list in Review to start shopping.','Chưa có đơn đang mua. Gửi danh sách trong mục Xem lại.')}</div>`;const history=state.orders.filter(x=>x!==o);$('#historyOrders').innerHTML=history.map(x=>orderHtml(x,false)).join('')||`<p class="muted">${t('No previous orders.','Chưa có đơn cũ.')}</p>`}
function adjustDraft(id,delta){const current=quantity(id),next=Math.max(0,Math.min(999,current+delta));if(current===next)return;const p=product(id),prev=state.draft.find(x=>String(x.id)===String(id));write('adjustItem',{id,qty:String(delta),name:p?.vi||prev?.name||'',unit:p?.unit||prev?.unit||'bó'},()=>{state.draft=state.draft.filter(x=>String(x.id)!==String(id));if(next)state.draft.push({id,name:p?.vi||prev?.name||'',en:p?.en||prev?.en||'',unit:p?.unit||prev?.unit||'bó',image:p?.image||prev?.image||'',qty:next})})}
function adjustOrder(oid,id,delta){const o=state.orders.find(x=>String(x.orderId)===String(oid));if(!o||o.status==='Completed')return;const i=o.items.find(x=>String(x.itemId)===String(id)),p=product(id),next=Math.max(0,Math.min(999,Number(i?.qty||0)+delta));if(i&&next===Number(i.qty))return;if(!next&&o.items.length<=1){toast(t('An order needs at least one item','Đơn cần ít nhất một món'));return}write('adjustOrderItem',{orderId:oid,id,qty:String(delta),name:p?.vi||i?.name||'',unit:p?.unit||i?.unit||'bó'},()=>{o.items=o.items.filter(x=>String(x.itemId)!==String(id));if(next)o.items.push({...i,orderId:oid,itemId:id,name:p?.vi||i?.name||'',en:p?.en||i?.en||'',unit:p?.unit||i?.unit||'bó',image:p?.image||i?.image||'',qty:next,bought:!!i?.bought})})}
function toggleFav(id){const isFav=state.favorites.includes(id);write('favorite',{id},()=>{state.favorites=isFav?state.favorites.filter(x=>x!==id):[...state.favorites,id]});toast(isFav?t('Removed from favourites','Đã bỏ yêu thích'):t('Saved to favourites','Đã lưu yêu thích'))}
function toggleBought(oid,id){const o=state.orders.find(x=>String(x.orderId)===String(oid)),i=o?.items.find(x=>String(x.itemId)===String(id));if(!i)return;write('bought',{orderId:oid,id},()=>{i.bought=!i.bought})}
function openSettings(){ $('#endpoint').value=cfg.url;$('#pin').value=cfg.pin;$('#modalShade').classList.remove('hidden')}
function closeSettings(){$('#modalShade').classList.add('hidden')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.page)setPage(b.dataset.page);
 else if(b.dataset.lang){lang=b.dataset.lang;localStorage.setItem('rce_lang',lang);render()}
 else if(b.dataset.filter){filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));renderProducts()}
 else if(b.dataset.fav)toggleFav(b.dataset.fav);
 else if(b.dataset.adjust)adjustDraft(b.dataset.adjust,Number(b.dataset.delta));
 else if(b.dataset.draftId)adjustDraft(b.dataset.draftId,Number(b.dataset.delta));
 else if(b.dataset.orderId)adjustOrder(b.dataset.oid,b.dataset.orderId,Number(b.dataset.delta));
 else if(b.dataset.addOrder){const id=$('#orderAddSelect')?.value;if(id)adjustOrder(b.dataset.addOrder,id,1)}
 else if(b.dataset.note){const o=state.orders.find(x=>String(x.orderId)===b.dataset.note),note=prompt(t('Edit shopping note','Sửa ghi chú'),o?.note||'');if(note!==null)write('editOrderNote',{orderId:b.dataset.note,note},()=>{o.note=note})}
 else if(b.dataset.finish){if(confirm(t('Finish this shopping trip?','Đã đi chợ xong?'))){const o=state.orders.find(x=>String(x.orderId)===b.dataset.finish);write('completeOrder',{orderId:b.dataset.finish},()=>{o.status='Completed'})}}
 else if(b.dataset.repeat){if(confirm(t('Copy these items into a new draft?','Chép các món này vào danh sách mới?')))write('repeat',{orderId:b.dataset.repeat}).then(ok=>{if(ok)setPage('review')})}
});
// Order buttons carry both data-order-id (order ID) and data-order-id? Use data-order-item for item IDs.
document.addEventListener('change',e=>{const x=e.target;if(x.matches('[data-bought]'))toggleBought(x.dataset.oid,x.dataset.bought)});
$('#search').addEventListener('input',renderProducts);
$('#customForm').addEventListener('submit',e=>{e.preventDefault();const nm=$('#customName').value.trim();if(!nm)return;const id='custom_'+nm.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').slice(0,70),unit=$('#customUnit').value;const n=quantity(id)+1;write('setItem',{id,name:nm,unit,qty:String(n)},()=>{state.draft=state.draft.filter(x=>String(x.id)!==id);state.draft.push({id,name:nm,en:'',unit,qty:n,image:''})}).then(ok=>{if(ok){$('#customName').value='';toast(t('Item added','Đã thêm món'))}})});
$('#submitOrder').addEventListener('click',async()=>{if(!state.draft.length)return;if(writeCount){toast(t('Wait for items to finish saving','Đợi lưu xong các món'));return}if(!confirm(t('Submit this list? You can edit it later.','Gửi danh sách này? Bạn vẫn có thể sửa sau.')))return;const ok=await write('submit',{note:$('#draftNote').value});if(ok){$('#draftNote').value='';setPage('shop');toast(t('Order submitted','Đã gửi danh sách'))}});
$('#bottomAction').addEventListener('click',()=>setPage(page==='review'?'choose':'review'));
$('#settings').addEventListener('click',openSettings);$('#connection').addEventListener('click',()=>cfg.pin?sync(true):openSettings());$('#closeModal').addEventListener('click',closeSettings);
$('#saveConnection').addEventListener('click',()=>{cfg.url=$('#endpoint').value.trim();cfg.pin=$('#pin').value;localStorage.setItem('rce_url',cfg.url);localStorage.setItem('rce_pin',cfg.pin);closeSettings();sync(true)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});window.addEventListener('online',()=>sync());setInterval(()=>{if(!document.hidden&&cfg.pin)sync()},30000);
render();if(cfg.pin)sync(true);else connection(t('Tap to connect','Nhấn để kết nối'),'bad');
